language: node_js
os: linux

git:
  depth: 3

branches:
  only:
    - master
    - stable
  except:
    - legacy
    - experimental

before_install:
  - python

install:
  - yarn install

script:
  - yarn deploy
  - yarn test

before_script:
  - yarn test

after_script:
  - yarn clean

cache:
  directories:
    - node_modules

